export const DECREMENT_COUNTER_CC = 'DECREMENT_COUNTER_CCJ';
export const INCREMENT_COUNTER_CC = 'INCREMENT_COUNTER_CC';
export const DECREMENT_COUNTER_FC = 'DECREMENT_COUNTER_FC';
export const INCREMENT_COUNTER_FC = 'INCREMENT_COUNTER_FC';
